-- CreateTable
CREATE TABLE `Listing` (
    `sourceId` VARCHAR(191) NOT NULL,
    `source` VARCHAR(191) NOT NULL DEFAULT 'sprzedajemy',
    `url` TEXT NOT NULL,
    `title` VARCHAR(500) NOT NULL,
    `description` TEXT NOT NULL,
    `city` VARCHAR(100) NOT NULL,
    `district` VARCHAR(100) NULL,
    `price` INTEGER NOT NULL,
    `pricePerM2` INTEGER NOT NULL,
    `isNegotiable` BOOLEAN NOT NULL,
    `area` DOUBLE NOT NULL,
    `rooms` INTEGER NOT NULL,
    `floor` INTEGER NOT NULL,
    `totalFloors` INTEGER NULL,
    `yearBuilt` INTEGER NULL,
    `marketType` ENUM('primary', 'secondary') NOT NULL,
    `buildingType` VARCHAR(50) NULL,
    `ownershipForm` VARCHAR(50) NULL,
    `heating` VARCHAR(50) NULL,
    `sellerType` ENUM('private', 'agency') NOT NULL,
    `hasElevator` BOOLEAN NOT NULL,
    `amenities` JSON NOT NULL,
    `images` JSON NOT NULL,
    `imageCount` INTEGER NOT NULL,
    `AI_resume` TEXT NULL,
    `contentHash` VARCHAR(64) NULL,
    `fetchedAt` DATETIME(3) NOT NULL,
    `normalizedAt` DATETIME(3) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `Listing_city_price_idx`(`city`, `price`),
    INDEX `Listing_rooms_idx`(`rooms`),
    INDEX `Listing_marketType_idx`(`marketType`),
    PRIMARY KEY (`sourceId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
